
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200	

; board_build
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

upload_protocol = esptool 

board_upload.flash_size = 4MB

upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101

lib_deps = 
	moononournation/GFX Library for Arduino@1.4.4

monitor_filters =
    esp32_exception_decoder
	time
    colorize

build_type = debug

build_flags =
	-D LV_CONF_INCLUDE_SIMPLE
	-Iinclude
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1